# Generated by Django 5.1.4 on 2024-12-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("processor", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=50)),
                ("storage", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="laptops/")),
            ],
        ),
    ]
